In [3]:
import yfinance as yf
from datetime import date

In [ ]:
symbols = [ 'AAPL', 'META' ]
testhist = yf.download(symbols, start=date(2026,1,1), end=date(2026,4,1), interval='1d', auto_adjust=True)

[*********************100%***********************]  2 of 2 completed

In [31]:
testhist.shape

(61, 10)

In [32]:
testhist

Price            Close                    High                     Low  \
Ticker            AAPL        META        AAPL        META        AAPL
Date
2026-01-02  270.756653  649.853577  277.580254  663.821659  268.748522
2026-01-05  267.010162  658.226440  271.256189  663.971522  265.891214
2026-01-06  262.114716  660.054871  267.299866  664.950703  261.874950
2026-01-07  260.086609  648.135071  263.433483  658.586145  259.567106
2026-01-08  258.797852  645.507324  259.047618  646.546413  255.460962
...                ...         ...         ...         ...         ...
2026-03-25  252.619995  594.890015  255.000000  603.669983  251.600006
2026-03-26  252.889999  547.539978  257.000000  583.000000  250.770004
2026-03-27  248.800003  525.719971  255.490005  543.599976  248.070007
2026-03-30  246.630005  536.380005  250.869995  539.549988  245.509995
2026-03-31  253.789993  572.130005  255.479996  573.690002  247.100006

Price                         Open                Volume
Ticker            META        AAPL        META      AAPL      META
Date
2026-01-02  642.949515  272.005484  662.163045  37838100  13726500
2026-01-05  647.195906  270.387007  650.453127  45647200  12213700
2026-01-06  651.342359  266.750392  659.005781  52352100  11074400
2026-01-07  644.258385  262.953951  655.079138  48309800  12846300
2026-01-08  635.176143  256.779720  645.327486  50419300  11921700
...                ...         ...         ...       ...       ...
2026-03-25  593.400024  254.100006  598.739990  28476700  12585000
2026-03-26  543.349976  252.119995  582.489990  41796700  35780100
2026-03-27  520.260010  253.899994  540.099976  47900000  30133000
2026-03-30  528.539978  250.070007  536.380005  39446200  22795200
2026-03-31  546.770020  247.910004  549.979980  49598100  32898300

[61 rows x 10 columns]

In [33]:
testhist.columns

MultiIndex([( 'Close', 'AAPL'),
            ( 'Close', 'META'),
            (  'High', 'AAPL'),
            (  'High', 'META'),
            (   'Low', 'AAPL'),
            (   'Low', 'META'),
            (  'Open', 'AAPL'),
            (  'Open', 'META'),
            ('Volume', 'AAPL'),
            ('Volume', 'META')],
           names=['Price', 'Ticker'])

In [34]:
newhist = testhist.drop(labels=["High", "Low", "Open"], axis=1)
newhist

Price            Close                Volume
Ticker            AAPL        META      AAPL      META
Date
2026-01-02  270.756653  649.853577  37838100  13726500
2026-01-05  267.010162  658.226440  45647200  12213700
2026-01-06  262.114716  660.054871  52352100  11074400
2026-01-07  260.086609  648.135071  48309800  12846300
2026-01-08  258.797852  645.507324  50419300  11921700
...                ...         ...       ...       ...
2026-03-25  252.619995  594.890015  28476700  12585000
2026-03-26  252.889999  547.539978  41796700  35780100
2026-03-27  248.800003  525.719971  47900000  30133000
2026-03-30  246.630005  536.380005  39446200  22795200
2026-03-31  253.789993  572.130005  49598100  32898300

[61 rows x 4 columns]